spring:
  application:
    name: msclientes

server:
  port: 0 #porta 0 significa uma porta randômica, para não precisar especificar a porta nas outras vezes que for subir

#aqui especifica onda está o endereco do eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ekoecsrurs-aurms-ue@localhost:8761/eureka
  instance:
     instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log