spring:
  application:
    name: mscartoes
  rabbitmq:
    host: ${RABBITMQ_SERVER} #trocou o nome de microserviço por uma variável de ambiente
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:     #para se autenticar no Eureka basta usar usuario e senha com o @
      defaultZone: http://cursoms-eureka-user:ekoecsrurs-aurms-ue@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

#configuracao para mensageria pelo RabbitMQ
mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log